#!/bin/bash

# Text color variables
txtund=$(tput sgr 0 1)    # Underline
txtbld=$(tput bold)       # Bold
txtred=$(tput setaf 1)    # Red
txtgrn=$(tput setaf 2)    # Green
txtylw=$(tput setaf 3)    # Yellow
txtblu=$(tput setaf 4)    # Blue
txtpur=$(tput setaf 5)    # Purple
txtcyn=$(tput setaf 6)    # Cyan
txtwht=$(tput setaf 7)    # White
txtrst=$(tput sgr0)       # Text reset

#COMMIT_ID=`cat - | ~/bin/get_commit_id.sh`
COMMIT_ID=`cat - | grep -i "commit:" | head -n 1 | sed -s 's/ //g' | cut -f 2 -d ':'`
#echo "$COMMIT_ID"
#exit

C2P=`which c2p`

echo "${txtblu}c2p $COMMIT_ID${txtrst}"
#gnome-terminal --command="${C2P} $COMMIT_ID" --geometry=120x30 &
gnome-terminal --command="${C2P} $COMMIT_ID" &
exit
