#!/bin/bash

REAL_SCRIPT=$(realpath -e "${BASH_SOURCE[0]}")
SCRIPT_TOP="${SCRIPT_TOP:-$(dirname "${REAL_SCRIPT}")}"
cd ${SCRIPT_TOP}
echo "${SCRIPT_TOP}"

help()
{
	echo "$0 PATCH_NAME VERSION"
	exit 1
}

delete()
{
	local patch=$1
	local version=$2

	echo "deleting ${patch} from linux-${version} queue"

	cd linux-"${version}".y ||
		(echo "directory linux-${version}.y is not found" && return)

	found=$(quilt series | grep "${patch}")
	if [[ -z  "${found}" ]] ; then
		echo "patch ${patch} is not found in linux-${version}.y"
		cd ..
		return
	fi

	quilt pop -qf "${patch}"
#	quilt delete -r "${patch}"
	if ! quilt delete -r "${patch}" ; then
		echo "unable to delete patch ${patch} from linux-${version}.y"
		cd ..
		return
	fi
	qp -a
	cd ..
}

PATCH=$1
shift

if [[ -z "${PATCH}" ]]; then
	help
fi

if [[ "$#" == "0" ]]; then
	versions=$("./stable-queue/scripts/active_kernel_versions_get.sh")
else
	versions="$*"
fi

if [[ "${versions}" == "all" ]]; then
	echo "removing ${PATCH} from all versions..."
	for VERSION in $(cat stable-queue/active_kernel_versions)
	do
		delete "${PATCH}" "${VERSION}"
	done
else
	for VERSION in ${versions}
	do
		delete "${PATCH}" "${VERSION}"
	done
fi
