#!/bin/bash


help()
{
	echo "$0 PATCH_NAME VERSION"
	exit 1
}


delete()
{
	local patch=$1
	local version=$2

	echo "deleting ${patch} from linux-${version} queue"

	cd linux-${version}.y && quilt pop "${patch}" && quilt delete -r "${patch}" && qp -a

}

PATCH=$1

VERSION=$2

if [ "${VERSION}" == "" ] ; then
	help
fi

if [ "${PATCH}" == "" ] ; then
	help
fi

delete ${PATCH} ${VERSION}

