#!/bin/bash

VERSION=$1
if [ "$VERSION" == "" ] ; then
	echo "you need a version!"
	exit
fi
echo "VERSION=$VERSION"
DIR="queue-$VERSION"


# create a temp directory and copy the patches there
# FIXME, use a "real" temp directory name, not just tmp, as that messes things
# up when the script is run twice at the same time for different versions.
mkdir ../tmp
git ls-files -o | grep queue-$VERSION | xargs -i  cp {} -v ../tmp/

# create a commit message
# FIXME, use a "real" temporary file name, not just 'commit.msg'
echo "${VERSION}-stable patches" > commit.msg
echo "" >> commit.msg
echo "added patches:" >> commit.msg
for file in `ls ../tmp/`
do
	echo "	`basename $file`" >> commit.msg
done

# add the files and commit them to git
git add $DIR
git commit $DIR -F commit.msg
rm commit.msg

# do notification for the authors that the patches are now added to the tree.
for file in `ls ../tmp/`
do
	../added-to-stable-version $VERSION ../tmp/$file
done

# clean up
rm -rf ../tmp/

ONLINE=`gregkh_machine_online`
# Only push if we have a network connection
if [ "$ONLINE" = "1" ] ; then
	git push kroah.com master
	git push
fi
