#!/bin/bash

create_kernel() {
	VERSION=$1
	echo "building kernel ${VERSION}"
	cd linux-${VERSION}.y
	../stable-queue/scripts/quilt-mail mbox
}

for VERSION in $(cat active_kernel_versions); do
	create_kernel "${VERSION}" &
done

wait

echo "finished"

