#!/bin/bash

create_kernel() {
	VERSION=$1
	echo "building kernel ${VERSION}"
	cd linux-${VERSION}.y
	../stable-queue/scripts/quilt-mail mbox
}

create_kernel "4.4" &
create_kernel "4.9" &
create_kernel "4.14" &
create_kernel "4.19" &
create_kernel "5.4" &
create_kernel "5.6" &
wait
echo "finished"

