#!/bin/bash

VERSION=`ketchup -m`
HOST="gregkh@geb.kernel.org"

REL_ARRAY=(${VERSION//./ })
BASE=${REL_ARRAY[0]}.${REL_ARRAY[1]}.${REL_ARRAY[2]}
REL=${REL_ARRAY[3]}
MINOR=${REL_ARRAY[2]}

LONGTERM=0
# see if this is a "longterm" kernel or not
if [ $MINOR == "32" ]; then
	LONGTERM=1
fi
if [ $MINOR == "33" ]; then
	LONGTERM=1
fi
#echo "longterm = $LONGTERM"

# see if this is 3.X or 2.X
THREE=0
if [ ${REL_ARRAY[0]} == "3" ] ; then
	# 3.0
	THREE=1
fi

git diff HEAD --stat > diffstat
echo "# diffstat created"

git diff HEAD > patch-$VERSION
echo "# $VERSION patch created"

gpg -a -b patch-${VERSION}


DIR="stable-review"
if [ $LONGTERM -eq 1 ]; then
	DIR="longterm-review"
fi

if [ $THREE -eq 1 ]; then
	VER="3.0"
else
	VER="2.6"
fi
#echo "scp patch-$VERSION gregkh@master.kernel.org:v$VER/$DIR/"

echo "kup --host=${HOST} put patch-${VERSION} patch-${VERSION}.asc /pub/linux/kernel/v${VER}/${DIR}/patch-${VERSION}.gz"

