#!/bin/bash

# to move to a new major tree:
#
# git merge -s ours --no-commit v6.0.X
# git read-tree -um v6.0.X
# git commit -s -m "Merge..."
#

git checkout linux-6.12.y
ver=$(make kernelversion)
git checkout linux-rolling-lts
git merge --no-commit --signoff v$ver; GIT_AUTHOR_DATE=$(git log -1 --format="%aD" v$ver) GIT_COMMITTER_DATE=$(git log -1 --format="%cD" v$ver) git commit -s -m "Merge v$ver"

git checkout linux-6.14.y
ver=$(make kernelversion)
git checkout linux-rolling-stable
git merge --no-commit --signoff v$ver; GIT_AUTHOR_DATE=$(git log -1 --format="%aD" v$ver) GIT_COMMITTER_DATE=$(git log -1 --format="%cD" v$ver) git commit -s -m "Merge v$ver"

echo "git push origin linux-rolling-stable linux-rolling-lts"

