#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# Copyright 2018 Greg Kroah-Hartman <gregkh@linuxfoundation.org>
#
# Dig out patches that are created based on the "Fixes:" tag to match up with
# stuff that is also in the stable trees already.
#
# horribly messy right now, probably really inefficient and slow, and requires
# lots of manual setup and poking around in a mbox file afterward.  Use at your
# own risk...
#
# also is overly-enthusiastic, catching stuff that might not only be fixes in
# stable trees, but that's a good thing for now, we can live with that :)
#

HOME="/home/gregkh/linux"
TMPDIR="/home/gregkh/tmp"
PREFIX="fixes_search_"
FIXED_IN="/home/gregkh/linux/scripts/fix_in_what_release"


TMP_PREFIX="${TMPDIR}/${PREFIX}"

BASE_KERNEL="5.2"

#KERNEL_RANGE="v4.9..v4.10"
#KERNEL_RANGE="v4.14..v4.15"
#KERNEL_RANGE="v4.17..v4.18"
#KERNEL_RANGE="v4.15..v4.16"
#KERNEL_RANGE="v5.0..v5.1"
#KERNEL_RANGE="v5.1..v5.2"
KERNEL_RANGE="v5.2..HEAD"
#KERNEL_RANGE="v5.3-rc3..v5.3-rc4"

STABLE_KERNEL="${HOME}/stable/linux-${BASE_KERNEL}.y"
#STABLE_KERNEL="${HOME}/stable/linux-4.14.y"
LATEST_KERNEL="${HOME}/gregkh"

cd "${STABLE_KERNEL}"
STABLE_LOG=`mktemp ${TMP_PREFIX}stable_log.XXXXXX` || exit 1
git log v${BASE_KERNEL}..HEAD > "${STABLE_LOG}"

cd -

cd "${LATEST_KERNEL}"
GIT_LOG=`mktemp ${TMP_PREFIX}git_log.XXXXXX` || exit 1
git log --reverse --no-merges --format='%h' "${KERNEL_RANGE}" > ${GIT_LOG}

FIX_COMMITS=`mktemp ${TMP_PREFIX}fixes.XXXXXX` || exit 1
STABLE_COMMITS=`mktemp ${TMP_PREFIX}stable.XXXXXX` || exit 1
MBOX=`mktemp ${TMP_PREFIX}mbox.XXXXXX` || exit 1

COMMIT_LOG=`mktemp ${TMP_PREFIX}tmp_log.XXXXX` || exit 1

# find all commits that say they fix something in the tree that are not already
# in the stable tree
while read -r commit
do
	echo "commit = ${commit}"

	# is it in the log already?
	present=`grep -i "${commit}" "${STABLE_LOG}"`
	if [ "${present}" == "" ] ; then
		echo "	commit ${commit} is not present!"

		git log -1 --format='%b' ${commit} > ${COMMIT_LOG}

		# is this commit a "fix" for something already in this release?
		# fixme...
		fixes=`grep -i '^[[:space:]]*Fixes:' ${COMMIT_LOG}`
		if [[ ${fixes} =~ [[:xdigit:]]{12} ]] ; then
			fix_commit=${BASH_REMATCH}
#			fix_commit=`echo ${fixes} | sed -e 's/^[ \t]*//' | cut -f 2 -d ':' | sed -e 's/^[ \t]*//' | cut -f 1 -d ' '`
			echo "	fixes='${fixes}'"
			echo "	fix_commit='${fix_commit}'"


			# see if this fixes something we have already queued up in the stable tree
			stable_included=$(cd /home/gregkh/linux/stable/stable-queue && git grep ${fix_commit})
			cd "${LATEST_KERNEL}"
			if [ "${stable_included}" != "" ] ; then
				echo "	stable_included='${stable_included}'"
				git show --pretty=email ${commit} >> "${MBOX}"
			fi
		fi


		# is it a syzkaller reported patch?
#		git log -1 --format='%b' ${commit} | grep -i -E "(syzkaller|syzbot)" &> /dev/null
#		if [ $? -eq 0 ] ; then
#			#echo "${commit}" >> "${MBOX}"
#			git show --pretty=email ${commit} >> "${MBOX}"
#			echo "commit ${commit} is a syzkaller one!"
#		fi
	fi
done < "${GIT_LOG}"

rm ${GIT_LOG}
rm ${COMMIT_LOG}
rm ${FIX_COMMITS}
rm ${STABLE_COMMITS}
rm ${STABLE_LOG}

