#!/bin/sh
#
# installs a kernel
#
make modules_install

# fine out what kernel version this is
for TAG in VERSION PATCHLEVEL SUBLEVEL EXTRAVERSION ; do
    eval `sed -ne "/^$TAG/s/ //gp" Makefile`
done
SRC_RELEASE=$VERSION.$PATCHLEVEL.$SUBLEVEL$EXTRAVERSION

# figure out the arch
#ARCH=`grep "CONFIG_ARCH " include/linux/autoconf.h | cut -f 2 -d "\""`
#ARCH="i386"
ARCH="x86"

# copy the kernel image
cp arch/$ARCH/boot/bzImage /boot/bzImage-"$SRC_RELEASE"

# copy the System.map file
cp System.map /boot/System.map-"$SRC_RELEASE"
#ln -sf /boot/System.map-"$SRC_RELEASE" /boot/System.map

# delete the keys used for this kernel
rm certs/signing_key.*

echo "Installed $SRC_RELEASE for $ARCH"

#if [ -f "/etc/os-release" ]; then
#	source /etc/os-release
#fi
#
#if [ "${NAME}" = "Arch Linux" ]; then
#	# This is arch linux, so make the initrd
#	mkinitcpio -k ${SRC_RELEASE}-gregkh -g /boot/initramfs-${SRC_RELEASE}-gregkh.img
#fi
