#!/bin/bash
#
# Convert a mbox file into a review file as processed by voting_results
#
# Warning, almost no error checking, this is a hack to get things converted only.
#

in_file=$1
out_file=$2

shas=$(grep -i "^commit: " ${in_file} | grep -oE "[a-f0-9]{40,}")
for s in ${shas}; do
#	echo "writing ${s}"
#	git --git-dir=/home/gregkh/linux/stable/linux-stable/.git show --pretty=email ${s} >> ${out_file}
##	output=$(cd /home/gregkh/linux/stable/linux-stable && git show --pretty=email ${s})
##	echo ${output} >> ${out_file}
	oneline=$(git --git-dir=/home/gregkh/linux/stable/linux-stable/.git --no-pager log ${s} -n1 --format="%h")
#	oneline=$(git --git-dir=/home/gregkh/linux/stable/linux-stable/.git --no-pager log ${s} -n1 --format="%h %s")
	echo ${oneline} | tee -a ${out_file}
done
