#!/usr/bin/env -S just --justfile

# show the list of options
_help:
	@just --list

# Merge main into all branches
merge_main:
	#!/usr/bin/env bash
	cd {{invocation_directory()}}
	git merge main
	for branch in $(git branch --list --no-color | cut -f 3 -d ' '); do
		echo "Updating $branch"
		git checkout "${branch}"
		git merge main
	done

# Push all tags
push_tags:
	#!/usr/bin/env bash
	cd {{invocation_directory()}}
	for remote in $(git remote); do
		#git push "${remote}" --tags
		gum spin --title="Pushing tags to ${remote}" --align=right --show-output -s minidot --show-output -- git push "${remote}" --tags
	done

# push a specific branch/tags
push type:
	@cd {{invocation_directory()}}; ../scripts/push {{type}}

# push testing
pt:
	@cd {{invocation_directory()}}; ../scripts/push testing

# push all branches
push_all:
	@cd {{invocation_directory()}}; ../scripts/push all

# Generate a pull request
pull_request:
	@cd {{invocation_directory()}}; ../scripts/pull_request

# make pull message (obsolete)
make_message:
	@cd {{invocation_directory()}}; ../scripts/mk_msg x

# commit all for this branch
commit:
	@cd {{invocation_directory()}}; ../scripts/do.sh

# sync the working branches
work_sync:
	@cd {{invocation_directory()}}; ../scripts/work_sync
