#!/bin/bash

#git format-patch -k -M -N staging-next..HEAD


# get the name of the branch we are currently on
ref=$(git symbolic-ref HEAD 2> /dev/null) || return
BRANCH=${ref#refs/heads/}

# take off the right most '-2.6' portion of the directory name
PWD=`pwd`
BASENAME=`basename $PWD`
NAME_LEN=${#BASENAME}
NAME_GET=$((NAME_LEN - 4))
NAME=${BASENAME:0:$NAME_GET}
FOO=${BASENAME%-2.6}

echo $NAME
echo $FOO
echo $BRANCH

ROOT_BRANCH=`echo $BRANCH | cut -f 2 -d '-'`
echo $ROOT_BRANCH

echo "git format-patch -k -M -N $NAME-$ROOT_BRANCH..HEAD"
