#!/usr/bin/perl

use strict;

my $pwd = `pwd`;
chomp($pwd);
#print "pwd = $pwd\n";
my $tree = `basename $pwd`;
chomp($tree);
#print "tree = $tree\n";
my $version = `kv`;
chomp($version);

my $branch = `git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/' | cut -f2- -d '-' | cut -f2- -d '-'`;
# doesn't work because the sed regex isn't working due to quoting and I don't feel like figuring it out...
#my $branch = `git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/' | rev | cut -f2- -d '-' | rev `;
chomp($branch);
#print "$branch\n";

print "# What is the kernel version? [$version] ";
my $q = <STDIN>;
chomp($q);
if ($q eq "") {
	$q = $version;
}
print "git tag -u kroah.com -s $tree-$q $tree-$branch\n";
#print "git tag -u kroah.com -s $tree-$q $tree-next\n";
print "git push origin $tree-$q\n";
print "echo \"git request-pull master git://git.kernel.org/pub/scm/linux/kernel/git/gregkh/$tree.git/ $tree-$q > msg.txt\" > do.sh\n";
