#!/bin/bash

BRANCH=$1
if [ "$BRANCH" == "" ] ; then
	echo "must specify branch (linus, testing, next, master), or 'all' or 'tags'"
	exit 1
fi

if [ "${BRANCH}" == "help" ] ; then
	echo "linus testing next master all tags"
	exit 0
fi

CURRENT_BRANCH=`git symbolic-ref --short -q HEAD`

PWD=`pwd`
TREE=`basename ${PWD}`

# push tags only
if [ "${BRANCH}" == "tags" ] ; then
	for remote in `git remote`
	do
		git push ${remote} --tags
	done
	exit
fi

# push all branches
if [ "${BRANCH}" == "all" ] ; then
	${BASH_SOURCE[0]} master
	${BASH_SOURCE[0]} linus
	${BASH_SOURCE[0]} next
	${BASH_SOURCE[0]} testing
	exit
fi

if [ "${BRANCH}" == "master" ] ; then
	TO_PUSH="master"
else
	TO_PUSH="${TREE}-${BRANCH}"
fi

git checkout ${TO_PUSH}
for remote in `git remote`
do
	git push ${remote} ${TO_PUSH}
done

git checkout ${CURRENT_BRANCH}
