#!/bin/bash

CURRENT_BRANCH=`git symbolic-ref --short -q HEAD`
BRANCH="linus"

PWD=`pwd`
TREE=`basename ${PWD}`

git checkout ${TREE}-${BRANCH}
for remote in `git remote`
do
	git push ${remote} ${TREE}-${BRANCH}
done

git checkout ${CURRENT_BRANCH}
