#!/bin/bash

BRANCH=$1
if [ "$BRANCH" == "" ] ; then
	echo "must specify branch! (linus, testing, next)"
	exit 1
fi

CURRENT_BRANCH=`git symbolic-ref --short -q HEAD`

PWD=`pwd`
TREE=`basename ${PWD}`

git checkout ${TREE}-${BRANCH}
for remote in `git remote`
do
	git push ${remote} ${TREE}-${BRANCH}
done

git checkout ${CURRENT_BRANCH}
